### PR TITLE
[[ ExternalsApiV6 ]] Resolved a backwards compatibility issue

### PR DESCRIPTION
**Pull request by montegoulding**
Hi Sebastien

I found this issue when testing my externals build against this branch.

Cheers

Monte

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Hi Monte,
Thanks for noticing that.

**Comment by livecodesebastien** [comment]
Have you gone through any other issues regarding backwards compatibility that would need a new review of the runrevsebastien/bugfix-14057 branch?

**Comment by montegoulding** [comment]
not yet but I'm really hoping this stuff doesn't miss RC 3

**Comment by livecodesebastien** [comment]
We are now fighting with issues to get the 7.0.2 GM out as soon as possible, as for now it's not possible to upload any app on the AppStore because of matching minimum versions issues (and the 64-bit requirement, not everyone using the RCs). The 7.0.3 RC 1 should follow really soon afterwards.

**Comment by montegoulding** [comment]
Well this is a complete blocker for anyone needing externals in LC 7. Could you at least pull in the fix to the type constants in the engine. That's the critical part I think.

**Pull request merged**
